[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Optimizer
optimizer = true
optimizer_runs = 50          # <— smaller code; try 1, 20, 50, 100
via_ir = true                # usually helps size; flip to false if size grows

# Misc
bytecode_hash = "none"       # strips metadata hash from creation bytecode
cbor_metadata = false        # strips CBOR metadata from creation bytecode

# Extra config recommended by OpenZeppelin -- https://docs.openzeppelin.com/upgrades-plugins/foundry-upgrades#before_running
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fuzz]
max_test_rejects = 4194304

[invariant]
shrink_run_limit = 0